### PR TITLE
disable noexcept-type warning

### PR DESCRIPTION
**Pull request by Karsten1987**
That's the only chance I've needed in order to compile ros2 master on ubuntu 18.04 with no warnings.
I know this not a target platform, but I thought I bring it up, because I think it's still valuable to compile on 18.04 without warnings.

I get quite a few warnings on 18.04 in the style of `will change in C++17 because the exception specification is part of a function type`:
```
/home/karsten/ros2_ws/src/ros2/rcutils/test/./mocking_utils/patch.hpp:236:11: error: mangled name for ‘mocking_utils::Patch<ID, ReturnT(ArgTs ...)>& mocking_utils::Patch<ID, ReturnT(ArgTs ...)>::operator=(mocking_utils::Patch<ID, ReturnT(ArgTs ...)>&&) [with long unsigned int ID = 5; ReturnT = int; ArgTs = {_IO_FILE*, char*, int, long unsigned int}]’ will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
   Patch & operator=(Patch && other)
           ^~~~~~~~
/home/karsten/ros2_ws/src/ros2/rcutils/test/./mocking_utils/patch.hpp:228:11: error: mangled name for ‘mocking_utils::Patch<ID, ReturnT(ArgTs ...)>& mocking_utils::Patch<ID, ReturnT(ArgTs ...)>::operator=(const mocking_utils::Patch<ID, ReturnT(ArgTs ...)>&) [with long unsigned int ID = 5; ReturnT = int; ArgTs = {_IO_FILE*, char*, int, long unsigned int}]’ will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
   Patch & operator=(const Patch &) = delete;
           ^~~~~~~~
/home/karsten/ros2_ws/src/ros2/rcutils/test/./mocking_utils/patch.hpp:227:3: error: mangled name for ‘mocking_utils::Patch<ID, ReturnT(ArgTs ...)>::Patch(const mocking_utils::Patch<ID, ReturnT(ArgTs ...)>&) [with long unsigned int ID = 5; ReturnT = int; ArgTs = {_IO_FILE*, char*, int, long unsigned int}]’ will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
   Patch(const Patch &) = delete;

```

### CODE REVIEW

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14428/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9199/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12100/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14528/)

**Comment by clalancette** [comment]
I can't say I'm a huge fan of disabling the warning, as it disables the warning on Ubuntu 20.04 (and macOS) as well.

Personally, I don't really see it as a problem that it throws a warning on an unsupported platform; that's part of the definition of unsupported.  As long as it compiles, warnings seem OK to me on Ubuntu 18.04.
