### PR TITLE
Add RCUTILS_ATOMIC_INIT for portable static initialisation

### PR DESCRIPTION
**Pull request by mjcarroll**
## Description

Apple clang rejects the brace-enclosed initialiser on the fault injection counter:

```
fault_injection.c:19:63: error: illegal initializer type
'atomic_int_least64_t' (aka '_Atomic(int_least64_t)')
```

The counter cannot be statically initialised with one spelling on every platform, because `atomic_int_least64_t` is not the same kind of type everywhere. The bundled shims define `_Atomic(T)` as a struct, so the initialiser has to be brace enclosed; with the native C11 `_Atomic` the type is scalar, and braces there are what clang rejects. Dropping the braces outright fixes clang but breaks MSVC with C2074.

The shims already carry an `ATOMIC_VAR_INIT` matched to their own `_Atomic`, so `RCUTILS_ATOMIC_INIT` just defers to it where it exists:

```c
#ifdef ATOMIC_VAR_INIT
#define RCUTILS_ATOMIC_INIT(value) ATOMIC_VAR_INIT(value)
#else
#define RCUTILS_ATOMIC_INIT(value) (value)
#endif
```

`ATOMIC_VAR_INIT` is only missing on the native header in C23 mode, which is exactly what broke the build in #553 (`implicit declaration of function 'ATOMIC_VAR_INIT'`). In that configuration `_Atomic` is the scalar that a plain value initialises, so the fallback is correct. This leaves both vendored shim headers untouched.

Covers the four configurations:

| header | `_Atomic` | `ATOMIC_VAR_INIT` | expansion |
| --- | --- | --- | --- |
| `win32/stdatomic.h` | struct | yes | `{.__val = (value)}` |
| `gcc/stdatomic.h`, `__CLANG_ATOMICS` | builtin scalar | yes | `(value)` |
| `gcc/stdatomic.h`, otherwise | struct | yes | `{ .__val = (value) }` |
| native `<stdatomic.h>`, C23 | scalar | no | `(value)` |

### Is this user-facing behavior change?

No behaviour change. It does add a macro to a public header.

### Additional Information

Verified the preprocessed expansion on the MSVC path is `{.__val = (-1)}`, and that it builds clean at `/W4 /WX` with MSVC 14.51. The gcc and clang paths need CI.

### CODE REVIEW

**Comment by mjcarroll** [comment]
--packages-up-to rcutils, --packages-select rcutils

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/30234/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/22928/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/10044/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/29096/)

**Review by wjwwood — APPROVED** [review]
lgtm

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/30244/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/22938/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/10054/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/29107/)

**Comment by wjwwood** [comment]
Needs AI attribution in description.

**Review by wjwwood — APPROVED** [review]

**Review by fujitatomoya — COMMENTED** [review]
@mjcarroll we already have the PR open for this issue: https://github.com/ros2/rcutils/pull/587. i do not mind either of them, please go ahead to pick one!

**Comment by mjcarroll** [comment]
Missed that! Closing this one out.
